vm.emulator.version=5.0.0-88 05.00.009 20210302
port=6622
cli_path=$WEBOS_CLI_TV
emulator_path=$LG_WEBOS_TV_SDK_HOME/Emulator/v5.0.0
vbox_path=$VBOX_INSTALL_PATH
uuid=9e8b9f29-44b9-4a6e-3053-2053a70341cb
helppage=http://webostv.developer.lge.com/sdk/tools/emulator/
hdid=8dcdf229-f189-4fd2-305f-f1fbb991a3ea
