var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[g]=d.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var g=0;return $jscomp.iteratorPrototype(function(){return g<c.length?{done:!1,value:c[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(c,g){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var d=0,l={next:function(){if(d<c.length){var a=d++;return{value:g(a,c[a]),done:!1}}l.next=function(){return{done:!0,value:void 0}};return l.next()}};l[Symbol.iterator]=function(){return l};return l};
$jscomp.polyfill=function(c,g,d,l){if(g){d=$jscomp.global;c=c.split(".");for(l=0;l<c.length-1;l++){var a=c[l];a in d||(d[a]={});d=d[a]}c=c[c.length-1];l=d[c];g=g(l);g!=l&&null!=g&&$jscomp.defineProperty(d,c,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6-impl","es3");
var async=require("async"),chalk=require("chalk"),createCsvWriter=require("csv-writer").createObjectCsvWriter,fs=require("fs"),npmlog=require("npmlog"),path=require("path"),streamBuffers=require("stream-buffers"),Table=require("easy-table"),util=require("util"),luna=require("./base/luna"),novacom=require("./base/novacom"),errHndl=require("./base/error-handler"),hasProperty=require("./util/property"),createDateFileName=require("./util/createFileName").createDateFileName;
(function(){function c(a,c){a.nReplies=1;a.session?(d.info("deviceInfo#makeSession()","already exist session"),c()):(d.info("deviceInfo#makeSession()","need to make new session"),a.session=new novacom.Session(a.device,c))}function g(a,c){if(null===a.outputPath)a.fileName=createDateFileName("_","csv"),a.destinationPath=path.resolve(".");else{var m=path.dirname(a.outputPath),g=path.parse(a.outputPath).base,b=path.parse(a.outputPath).ext,b=b.split(".").pop();d.info("deviceInfo#captureScreen()#_makeCaptureOption()dir name:"+
m+" ,file name:"+g+" ,inputFormat:"+b);if(g)if(a.fileName=g,a.destinationPath=path.resolve(m),""===b)a.fileName+=".csv";else{if("csv"!==b)return c(errHndl.changeErrMsg("INVALID_CSV_FORMAT"))}else m&&(a.fileName=createDateFileName("_","csv"),a.destinationPath=path.resolve(m))}a.csvPath=path.resolve(a.destinationPath,a.fileName);d.verbose("device#makeCSVOutputPath()","csvPath:",a.csvPath);fs.open(a.csvPath,"w",function(b,p){if(b)return c(errHndl.changeErrMsg(b));fs.close(p,function(p){if(p)return c(errHndl.changeErrMsg(p));
d.verbose("device#makeCSVOutputPath()",a.csvPath+" is closed");fs.existsSync(a.csvPath)&&fs.unlinkSync(a.csvPath);d.verbose("device#makeCSVOutputPath()",a.csvPath+" is exist: "+fs.existsSync(a.csvPath));c()})})}var d=npmlog;d.heading="deviceInfo";d.level="warn";var l={log:d,systemInfo:function(a,m){function g(c){d.verbose("deviceInfo#systemInfo#_getConfigs()");var b=a.session.getDevice().lunaAddr.deviceInfoConfig;luna.sendWithoutErrorHandle(a,b,{configNames:"tv.model.modelname tv.nyx.platformVersion tv.nyx.firmwareVersion tv.hw.SoCChipType tv.nyx.tvBroadcastSystem tv.rmm.grpCodeName".split(" "),
subscribe:!1},function(a,p){d.silly("deviceInfo#systemInfo#_getConfigs():","lineObj:",a);if(a)if(a.returnValue)if(a.configs){d.verbose("deviceInfo#systemInfo#_getConfigs():","success");var b;b=a.configs;d.verbose("deviceInfo#systemInfo#__makeConfigObj()");var c="";hasProperty(b,"tv.model.modelname")&&(c+="modelName : "+b["tv.model.modelname"]+"\n");hasProperty(b,"tv.nyx.platformVersion")&&(c+="sdkVersion : "+b["tv.nyx.platformVersion"]+"\n");hasProperty(b,"tv.nyx.firmwareVersion")&&(c+="firmwareVersion : "+
b["tv.nyx.firmwareVersion"]+"\n");var k="";hasProperty(b,"tv.hw.SoCChipType")&&(k+=b["tv.hw.SoCChipType"]);hasProperty(b,"tv.nyx.tvBroadcastSystem")&&(k+="_"+b["tv.nyx.tvBroadcastSystem"]);hasProperty(b,"tv.rmm.grpCodeName")&&(k+="_"+b["tv.rmm.grpCodeName"]);""!==k&&(c+="boardType : "+k+"\n");d.verbose("__makeConfigObj:",c);b=c.trim();p(null,b)}else d.verbose("deviceInfo#systemInfo#_getConfigs():","configs not exist"),p(errHndl.changeErrMsg("FAILED_CALL_LUNA","missingConfigs"));else d.verbose("deviceInfo#systemInfo#_getConfigs():",
"failure"),p(errHndl.changeErrMsg("FAILED_CALL_LUNA",a.errorText?a.errorText:a.errorMessage?a.errorMessage:""));else p(errHndl.changeErrMsg("INVALID_OBJECT"))},c)}if("function"!==typeof m)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(m));a=a||{};async.series([function(d){c(a,d)},function(c){d.verbose("deviceInfo#systemInfo#_getSystemInfo()");var b=a.session.getDevice().lunaAddr.deviceInfoSystem,k={keys:["modelName","sdkVersion","firmwareVersion","boardType","otaId"],subscribe:!1};
luna.sendWithoutErrorHandle(a,b,k,function(a,b){d.silly("deviceInfo#systemInfo#_getSystemInfo():","lineObj:",a);var c;if(a){c=k.keys;d.verbose("deviceInfo#systemInfo#__makeReturnObj()");var p="",e;for(e in c)hasProperty(a,c[e])&&(p+=c[e]+" : "+a[c[e]]+"\n");d.silly("__makeReturnObj():",p);c=p.trim();0<c.length?(d.verbose("deviceInfo#systemInfo#_getSystemInfo():","success"),b(null,c)):(d.silly("deviceInfo#systemInfo#_getSystemInfo():","resultValue is empty"),d.verbose(errHndl.changeErrMsg("FAILED_CALL_LUNA",
a.errorText?a.errorText:a.errorMessage?a.errorMessage:"")),g(b))}else b(errHndl.changeErrMsg("INVALID_OBJECT"))},c)}],function(a,b){m(a,b[1])})},systemResource:function(a,m){function l(){d.info("deviceInfo#systemResource()#_callSystemResourceInfoCmd()");var c=new streamBuffers.WritableStreamBuffer;try{a.session.run('date "+%Y-%m-%d %H:%M:%S"; grep -c ^processor /proc/cpuinfo; grep "cpu *" /proc/stat; free -k',null,c,null,function(a){if(a)return d.silly("deviceInfo#systemResource()#_callSystemResourceInfoCmd()",
"ssh call. err:"+a.toString()),m();var p=c.getContentsAsString();d.info("deviceInfo#systemResource()#_callSystemResourceInfoCmd()");a=/\s+/;var k={},z={},e={};try{var g=p.split("\n"),q=g[0],n=100*+g[1],h,f,p=!1;for(h=2;h<g.length-1;h++){f=g[h].split(a);if(0===f[0].indexOf("cpu")){var l="prev"+f[0]+"Total",O="prev"+f[0]+"Idle",P="prev"+f[0]+"User",I="prev"+f[0]+"Kernel",v="prev"+f[0]+"Other";b[l]||(b[l]=0,b[O]=0,b[P]=0,b[I]=0,b[v]=0);var A=parseInt(f[1]),Q=parseInt(f[2]),R=parseInt(f[3]),B=parseInt(f[4]),
E=Q+parseInt(f[5])+parseInt(f[6])+parseInt(f[7])+parseInt(f[8])+parseInt(f[9])+parseInt(f[10]),K=A+Q+R+B+E;if(!b.initialExecution){var D=K-b[l],F=(A-b[P])/D*100,u=(R-b[I])/D*100,x=(E-b[v])/D*100,w=(D-(B-b[O]))/D*100;0>F?F=0:F;F>n?F=n:F;0>u?u=0:u;u>n?u=n:u;0>x?x=0:x;x>n?x=n:x;0>w?w=0:w;w>n?w=n:w;k[f[0]]={overall:+w.toFixed(2),usermode:+F.toFixed(2),kernelmode:+u.toFixed(2),others:+x.toFixed(2)}}b[O]=B;b[P]=A;b[I]=R;b[v]=E;b[l]=K}b.initialExecution||(f[5]&&-1!==f[5].indexOf("buff/cache")&&(p=!0),0===
f[0].indexOf("Mem:")&&(z.memory=p?{total:+f[1],used:+f[2],free:+f[3],shared:+f[4],buff_cache:+f[5],available:+f[6]}:{total:+f[1],used:+f[2],free:+f[3],shared:+f[4],buffers:+f[5],cached:+f[6]}),0===f[0].indexOf("-/+")&&(z.buffers={used:+f[2],free:+f[3]}),0===f[0].indexOf("Swap:")&&(z.swap={total:+f[1],used:+f[2],free:+f[3]}))}b.initialExecution||(e={date:q,cpuinfo:k,meminfo:z},J(e))}catch(G){d.silly("deviceInfo#systemResource()#_setSystemResouceInfo()","in try-catch. err:",G.toString())}b.initialExecution=
!1})}catch(p){return d.silly("deviceInfo#systemResource()#_callSystemResourceInfoCmd()","in try-catch. err:",p.toString()),m()}}function J(b){function c(){console.log(b.date+"\n");console.log(g.toString());console.log(e.toString());console.log("=================================================================")}var k=b.cpuinfo,y=b.meminfo,g=new Table,e=new Table,l=[],q;for(q in k)g.cell("(%)",q),g.cell("overall",k[q].overall),g.cell("usermode",k[q].usermode),g.cell("kernelmode",k[q].kernelmode),g.cell("others",
k[q].others),g.newRow(),l.push({time:b.date,cpu:q,overall:k[q].overall,usermode:k[q].usermode,kernelmode:k[q].kernelmode,others:k[q].others});for(var n in y)e.cell("(KB)",n),e.cell("total",y[n].total),e.cell("used",y[n].used),e.cell("free",y[n].free),e.cell("shared",y[n].shared),e.cell("buff/cache",y[n].buff_cache),e.cell("available",y[n].available),e.newRow(),l.push({time:b.date,memory:n,total:y[n].total,used:y[n].used,free:y[n].free,shared:y[n].shared,"buff/cache":y[n].buff_cache,available:y[n].available});
if(a.save&&a.csvPath){var h=!1;fs.existsSync(a.csvPath)&&(h=!0);createCsvWriter({path:a.csvPath,header:[{id:"time",title:"time"},{id:"cpu",title:"(%)"},{id:"overall",title:"overall"},{id:"usermode",title:"usermode"},{id:"kernelmode",title:"kernelmode"},{id:"others",title:"others"},{id:"memory",title:"(KB)"},{id:"total",title:"total"},{id:"used",title:"used"},{id:"free",title:"free"},{id:"shared",title:"shared"},{id:"buff/cache",title:"buff/cache"},{id:"available",title:"available"}],append:h}).writeRecords(l).then(function(){d.silly("deviceInfo#systemResource()#_printSystemInfo()",
"CSV file updated");if(!1===h){var b="Create "+chalk.green(a.fileName)+" to "+a.destinationPath;console.log(b)}c()})["catch"](function(a){return setImmediate(m,errHndl.changeErrMsg(a))})}else c()}if("function"!==typeof m)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(m));var b={initialExecution:!0};a=a||{};a.destinationPath="";a.fileName="";a.csvPath="";async.series([function(b){a.save&&""===a.csvPath?g(a,b):b()},function(b){c(a,b)},function(b){d.info("deviceInfo#systemResource()#_getSystemResouceInfo()");
var c;if(a.interval)try{var k=0;c=setTimeout(function e(){1>k?(l(),k++,c=setTimeout(e,1E3)):(l(),c=setTimeout(e,1E3*a.interval))},100)}catch(z){return d.silly("deviceInfo#systemResource()#_getSystemResouceInfo()","repeat timer. err:",z.toString()),clearTimeout(c),b()}else{var g=0;try{c=setTimeout(function e(){if(2>g)l(),g++,c=setTimeout(e,1E3);else return clearTimeout(c),b()},100)}catch(z){return d.silly("deviceInfo#systemResource()#_getSystemResouceInfo()","one timer. err:",z.toString()),clearTimeout(c),
b()}}}],function(a,b){d.silly("deviceInfo#systemResource()","err:",a,", results:",b);m(a)})},processResource:function(a,l){function m(){d.info("deviceInfo#processResource()#_callProcessInfoCmd()");var c=new streamBuffers.WritableStreamBuffer;try{a.session.run("date \"+%Y-%m-%d %H:%M:%S\"; grep \"cpu *\" /proc/stat | sed \"1d\" | awk '{for (i=0;i<NR;i++){if(i==NR-1){totalSum+=$2+$3+$4+$5+$6+$7+$8+$9+$10+$11;idleSum+=$5}}} END { for (i=0;i<NR;i++){if(i==NR-1){print idleSum;print totalSum}}}'; cat /proc/[0-9]*/stat; echo 'psList' ;  ps -ax | sed \"1d\" | awk '/ /{print $1 \"\t\"$5}'; echo 'serviceStringStart'; ls /media/developer/apps/usr/palm/services ; echo 'serviceStringEnd'; luna-send-pub -n 1 -f luna://com.webos.applicationManager/dev/running '{}'; grep -c ^processor /proc/cpuinfo",
null,c,null,function(a){if(a)return d.silly("deviceInfo#processResource()#_callProcessInfoCmd()","ssh call. err:",a.toString()),l(null);var k=c.getContentsAsString();a:{d.info("deviceInfo#processResource()#_setProcessInfo()");var g=/\s+/;try{a=["Service","System"];for(var p=[],e={},m=[],q=0;q<a.length;q++)e[a[q]]={},e[a[q]].pid=0,e[a[q]].cputime=0,e[a[q]].RSS=0,e[a[q]].pmem=0;var q=[],n=[],h=k.split("\n"),f=[],ia=h[0];h.splice(h.length-1,1);for(var O=100*+h[h.length-1],k=0,P=+h[1],I=+h[2],v=h.indexOf("psList",
2),A=h.indexOf("serviceStringStart",2),Q=h.indexOf("serviceStringEnd",2),R=[],B=A+1;B<Q;B++)R[B-A-1]=h[B];Q=0;for(B=v+1;B<A;B++){var E=h[B].trim().split(g),K=parseInt(E[0]),D=E[1].trim();if(-1!==R.indexOf(D)){var F={processid:K,id:D};m[Q++]=F}}var u=h.indexOf("{",2);if(0>u)d.silly("deviceInfo#processResource()#_setProcessInfo()","running app list is invalid");else{for(var x=h.length-1,A="",w;u<x;u++)A+=h[u];try{w=JSON.parse(A)}catch(ba){d.silly("deviceInfo#processResource()#_setProcessInfo()","active app parsing. err:",
ba.toString());break a}if(!1===w.returnValue)l(errHndl.changeErrMsg("FAILED_CALL_LUNA",w.errorText||"running app list is invalid"));else{var G=w.running,x={};for(w=3;w<v;w++){var S=h[w].trim().split(g),D=S[1].trim().split(/.*\(|\)/gi)[1],u=void 0;switch(D){case "ls-hubd":u="Service";break;default:u="Other"}var K=parseInt(S[0]),A=D,ja=parseInt(S[3]),ea=parseInt(S[13])+parseInt(S[14]),Y=4*parseInt(S[23]),E=100*Y,k=k+Y;"Other"===u?f.push({pid:K,pname:A,ppid:ja,cputime:ea,RSS:Y,pmem:E}):(e[u].pid=K,e[u].cputime+=
ea,e[u].RSS+=Y,e[u].pmem+=E)}for(var L in e)if(h=L,"System"!==h)for(var T=e[L],v=0;v<f.length;v++)T.pid===f[v].ppid&&(e[h].pid=f[v].pid,e[h].cputime+=f[v].cputime,e[h].RSS+=f[v].RSS,e[h].pmem+=f[v].pmem,f.splice(v,1),v--);L=0;if(0===G.length)for(var M in b)hasProperty(b,M)&&0<=M.indexOf("prev_app_")&&(b[M]=void 0);else for(M=0;M<G.length;M++){var H=G[M],C=H.webprocessid,Z=H.processid,r=void 0;if(""!==C&&void 0!==C&&"undefined"!==C)r=C;else if(""!==Z&&void 0!==Z&&"undefined"!==Z)r=Z;else break;for(var t=
"prev_app_"+r+"cputime",U=parseInt(r),h=T=0;h<f.length;h++)if(f[h].pid===U){T=f[h].cputime;if(!b[t]){b[t]=T;break}var V=100*(T-b[t])/(I-b.prevTotalcputime);if(0>V||void 0===V||isNaN(V))V=0;L+=V;x[H.id+"-"+U]={id:H.id,pid:U,cpu:V,memory:{size:f[h].RSS,percent:f[h].pmem.toFixed(2)}};b[t]=T;f.splice(h,1);break}}if(0===m.length)for(var ca in b)hasProperty(b,ca)&&0<=ca.indexOf("prev_svc_")&&(b[ca]=void 0);else for(G=0;G<m.length;G++)for(var fa=m[G],r=fa.processid,t="prev_svc_"+r+"cputime",U=parseInt(r),
C=H=0;C<f.length;C++)if(f[C].pid===U){H=f[C].cputime;if(!b[t]){b[t]=H;break}var W=100*(H-b[t])/(I-b.prevTotalcputime);if(0>W||void 0===W||isNaN(W))W=0;L+=W;x[fa.id]={pid:U,cpu:W,memory:{size:f[C].RSS,percent:f[C].pmem.toFixed(2)}};b[t]=H;f.splice(C,1);break}for(r=0;r<f.length;r++)e.System.pid=f[r].pid,e.System.cputime+=f[r].cputime,e.System.RSS+=f[r].RSS,e.System.pmem+=f[r].pmem;if(!b.initialExecution){var da=I-b.prevTotalcputime,ka=(da-(P-b.prevIdlecputime))/da*100,ga;for(ga in e){r=ga;t=0;"Service"===
r&&(t=100*(e[r].cputime-b.prevServicecputime)/da);if(0>t||void 0===t||isNaN(t))t=0;L+=t;"System"===r&&(t=ka-L);0>t?t=0:t;t>O?t=O:t;e[r].pmem/=k;var la={pid:e[r].pid,appid:r,cpu:parseFloat(t.toFixed(2)),memory:{size:e[r].RSS,percent:e[r].pmem.toFixed(2)}};q.push(la)}for(var X in x)if(hasProperty(x,X)){var N=x[X],aa=parseFloat(N.cpu.toFixed(2));if(void 0===aa||isNaN(aa))aa=0;N.memory.percent/=k;var ha={pid:N.pid,appid:N.id||X,cpu:aa,memory:{size:N.memory.size,percent:parseFloat(N.memory.percent).toFixed(2)}};
q.push(ha);n.push(ha);0>q.indexOf(X)&&(a.push(X),p.push(X))}}b.prevIdlecputime=P;b.prevTotalcputime=I;b.prevServicecputime=e.Service.cputime;b.initialExecution||J({date:ia,processinfo:n,processList:p})}}}catch(ba){d.silly("deviceInfo#processResource()#_setProcessInfo()","in try-catch. err:",ba.toString())}}b.initialExecution=!1})}catch(p){return d.silly("deviceInfo#processResource()#_callProcessInfoCmd()","in try-catch. err:",p.toString()),l(null)}}function J(b){function c(){console.log(b.date+"\n");
console.log(g.toString());console.log("======================================================================")}d.info("deviceInfo#processResource()#_printProcessList()",JSON.stringify(b));var k=b.processinfo,g=new Table,m=!1;if(a.id&&(k.forEach(function(b){a.id===b.appid&&(m=!0)}),!1===m)){console.log("<"+a.id+"> is not running. Please launch the app or service.");return}if(0===b.processList.length)console.log("There are no running apps or services. Please launch any app or service.");else{var e=
[];Array.isArray(k)&&k.forEach(function(c){if(!a.id||a.id===c.appid){g.cell("PID",c.pid);g.cell("ID",c.appid);g.cell("CPU(%)",c.cpu);var d=c.memory;g.cell("MEMORY(%)",d.percent);g.cell("MEMORY(KB)",d.size);g.newRow();e.push({time:b.date,pid:c.pid,id:c.appid,cpu:c.cpu,memory:d.percent,memory_size:d.size})}});if(a.save&&a.csvPath){var J=!1;fs.existsSync(a.csvPath)&&(J=!0);createCsvWriter({path:a.csvPath,header:[{id:"time",title:"TIME"},{id:"pid",title:"PID"},{id:"id",title:"ID"},{id:"cpu",title:"CPU(%)"},
{id:"memory",title:"MEMORY(%)"},{id:"memory_size",title:"MEMORY(KB)"}],append:J}).writeRecords(e).then(function(){d.silly("deviceInfo#processResource()#_printProcessList()","CSV file updated");if(!1===J){var b="Create "+chalk.green(a.fileName)+" to "+a.destinationPath;console.log(b)}c()})["catch"](function(a){return setImmediate(l,errHndl.changeErrMsg(a))})}else c()}}if("function"!==typeof l)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(l));var b={initialExecution:!0};a=a||{};
a.destinationPath="";a.fileName="";a.csvPath="";async.series([function(b){a.save&&""===a.csvPath?g(a,b):b()},function(b){c(a,b)},function(b){d.info("deviceInfo#processResource()#_getProcessResouceInfo()");var c;if(a.interval)try{var g=0;c=setTimeout(function e(){1>g?(m(),g++,c=setTimeout(e,1E3)):(m(),c=setTimeout(e,1E3*a.interval))},100)}catch(z){return d.silly("deviceInfo#systemResource()#_getProcessResouceInfo()","repeat timer. err:",z.toString()),clearTimeout(c),b()}else{var k=0;try{c=setTimeout(function e(){if(2>
k)m(),k++,c=setTimeout(e,1E3);else return clearTimeout(c),b()},100)}catch(z){return d.silly("deviceInfo#systemResource()#_getProcessResouceInfo()","one timer. err:",z.toString()),clearTimeout(c),b()}}}],function(a,b){d.silly("deviceInfo#processResource()","err:",a,", results:",b);l(a)})}};"undefined"!==typeof module&&module.exports&&(module.exports=l)})();
