var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[g]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var g=0;return $jscomp.iteratorPrototype(function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,g){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var b=0,e={next:function(){if(b<a.length){var f=b++;return{value:g(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,g,b,e){if(g){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in b||(b[f]={});b=b[f]}a=a[a.length-1];e=b[a];g=g(e);g!=e&&null!=g&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
var util=require("util"),async=require("async"),path=require("path"),npmlog=require("npmlog"),novacom=require("./base/novacom"),luna=require("./base/luna"),errHndl=require("./base/error-handler"),hasProperty=require("./util/property"),installer=require("./install"),prefixPath="/media/developer/",prefixAppPath=prefixPath+"apps/usr/palm/applications",prefixServicePath=prefixPath+"apps/usr/palm/services",defaultGdbserverPort="9930";
(function(){var a=npmlog;a.heading="gdbserver";a.level="warn";var g={log:a,session:null,run:function(b,e,f){function g(c){a.verbose("gdbserver#_makeSession()");b.nReplies=1;b.session=new novacom.Session(b.device,c)}function p(c){a.verbose("gdbserver#run()#_getConfigs()");var d=b.session.getDevice().lunaAddr.deviceInfoConfig,h={configNames:["tv.nyx.platformVersion"],subscribe:!1};luna.sendWithoutErrorHandle(b,d,h,function(b,c){a.silly("gdbserver#run()#_getConfigs()","lineObj:",b);var d=b;d?d.returnValue?
d.configs&&hasProperty(d.configs,h.configNames[0])?(d=d.configs[h.configNames[0]],a.verbose("gdbserver#run()#_getConfigs()","sdkVersion:",d),d=d.split("."),d=Number(d[0]),c(null,d)):(a.verbose("gdbserver#run()#_getConfigs():","configs not exist"),c(errHndl.changeErrMsg("FAILED_CALL_LUNA","missingConfigs"))):(a.verbose("gdbserver#run()#_getConfigs()","failure"),c(errHndl.changeErrMsg("FAILED_CALL_LUNA",d.errorText?d.errorText:d.errorMessage?d.errorMessage:""))):c(errHndl.changeErrMsg("INVALID_OBJECT"))},
c)}function q(c,d){function h(a){"0"===(Buffer.isBuffer(a)?a.toString().trim():a.trim())?d(null,c):(c=Number(c)+1,q(c,d))}a.verbose("gdbserver#run()#_findNewDebugPort()","gdbPort:",c);null===c&&(c=n);"function"===typeof c&&(d=c,c=n);var e=util.format("netstat -ltn 2>/dev/null | grep :%s | wc -l",c);async.series([function(a){b.session.run(e,process.stdin,h,process.stderr,a)}],function(a){if(a)return d(a)})}if("function"!==typeof f)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(f));
var m=this,k=b.appId,l=b.serviceId,n=defaultGdbserverPort,t=b.port||defaultGdbserverPort;if(!k&&!l)return f(errHndl.changeErrMsg("EMPTY_VALUE","APP_ID"));var u=0;process.on("SIGINT",function(){a.verbose("This is SIGINT handling...");0<u++&&(a.verbose("To prevent hangup due to an abnormal disconnection"),process.exit(1));async.waterfall([g.bind(m),function(a,b){m.session=a;b()},m.getPidUsingPort.bind(m,m.port),m.killProcByPid.bind(m),function(a){m.session.end();setTimeout(a,500)}],function(a){a&&process.exit(1);
process.exit(0)})});async.waterfall([function(a){installer.list(b,function(d,h){h instanceof Array&&(b.instPkgs=h);a(d)})},g.bind(this),function(a,b){this.session=a;a.run("if ! type gdbserver > /dev/null; then echo 1; else echo 0; fi;",null,function(a){if("1"===(Buffer.isBuffer(a)?a.toString().trim():a.trim()))return b(Error("gdbserver command is not available in the target device"));setImmediate(b)},null,function(a){if(a)return setImmediate(b,a)})}.bind(this),function(c){a.verbose("gdbserver#run()#_getSdkVersion()");
var d=b.session.getDevice().lunaAddr.deviceInfoSystem,h={keys:["sdkVersion"],subscribe:!1};luna.sendWithoutErrorHandle(b,d,h,function(b,d){a.silly("gdbserver#run()#_getSdkVersion()","lineObj:",b);var c=b;c?hasProperty(c,h.keys[0])?(a.verbose("gdbserver#run()#_getSdkVersion()","sdkVersion:",c[h.keys[0]]),c=c[h.keys[0]],c=c.split("."),c=Number(c[0]),d(null,c)):(a.silly("gdbserver#run()#_getSdkVersion()","resultValue is empty"),a.verbose(errHndl.changeErrMsg("FAILED_CALL_LUNA",b.errorText?b.errorText:
b.errorMessage?b.errorMessage:"")),p(d)):d(errHndl.changeErrMsg("INVALID_OBJECT"))},c)}.bind(this),function(a,b){this.version=a;3<=this.version?b():b(errHndl.changeErrMsg("NOT_SUPPORT_GDBSERVER"))}.bind(this),function(c){function d(b){g=Buffer.isBuffer(b)?b.toString().trim():b.trim();if("{"===g[0])a.verbose("gdbserver#run()#_readAppInfo()","metaData:",g),c(null,g);else return c(errHndl.changeErrMsg("FAILED_GET_APPINFO"))}a.verbose("gdbserver#_readAppInfo()");var h=k||l;if(b.instPkgs){var e=k?"applications":
"services";b.instPkgs.every(function(a){return-1!==h.indexOf(a.id)?(prefixAppPath=prefixServicePath=path.join(path.dirname(a.folderPath),"..",e).replace(/\\/g,"/"),!1):!0})}var f;k?f=path.join(prefixAppPath,k,"appinfo.json"):l&&(f=path.join(prefixServicePath,l,"services.json"));f=f.replace(/\\/g,"/");var p="cat "+f;async.series([function(a){b.session.run(p,process.stdin,d,process.stderr,a)}],function(a){if(a)return c(errHndl.changeErrMsg("FAILED_GET_APPINFO"))});var g}.bind(this),function(b,d){a.verbose("gdbserver#run()#_getExecFileName()");
try{var c=JSON.parse(b);if(k){if(!c.main)return d(errHndl.changeErrMsg("INVALID_MAIN_FILE"));if("web"===c.type)return d(Error(c.id+" is not a native app"));this.execName=c.main}else if(l){if("native"!==c.engine)return d(Error(c.id+" is not a native service"));this.execName=c.executable}a.verbose("gdbserver#run()#_getExecFileName()","execName:",this.execName);d()}catch(r){d(r)}}.bind(this),this.getPidUsingPort.bind(this,n),this.killProcByPid.bind(this),q.bind(this,n),function(c,d){this.port=c;a.verbose("gdbserver#run()#_getEnvFromDevice()");
if("root"!==b.session.getDevice().username)setImmediate(d,null,"");else{a.verbose("gdbserver#run()#_getEnvFromDevice()","cmd:","find /etc/jail_native_devmode.conf 2>/dev/null | xargs awk '/setenv/{printf \"export %s=%s;\\n\", $2,$3}' | xargs echo");var h="";b.session.run("find /etc/jail_native_devmode.conf 2>/dev/null | xargs awk '/setenv/{printf \"export %s=%s;\\n\", $2,$3}' | xargs echo",null,function(a){h=Buffer.isBuffer(a)?h.concat(a.toString()):h.concat(a);setImmediate(d,null,h)},null,function(a){if(a)return setImmediate(d,
a)})}}.bind(this),function(b,d){a.verbose("gdbserver#run()#_addUserEnv()");var c;k?c={SDL_VIDEODRIVER:"wayland",XDG_RUNTIME_DIR:"/tmp/xdg",LD_LIBRARY_PATH:"$LD_LIBRARY_PATH:"+path.join(prefixAppPath,k,"lib").replace(/\\/g,"/")}:l&&(c={LD_LIBRARY_PATH:"$LD_LIBRARY_PATH:"+path.join(prefixServicePath,l,"lib").replace(/\\/g,"/")});c=b.concat(function(a){var b="";Object.keys(a).forEach(function(c){b=b.concat("export ").concat(c).concat("=").concat(a[c]).concat(";")});return b}(c));d(null,c)}.bind(this),
function(c,d){a.verbose("gdbserver#run()#_launchGdbserver()");var e;k?e=path.join(prefixAppPath,k):l&&(e=path.join(prefixServicePath,l));var f="";6===this.version?f="_ndk5":3<this.version&&(f="_ndk"+String(this.version));e=util.format("cd %s && gdbserver%s :%s %s",e,f,this.port,path.join(e,this.execName)).replace(/\\/g,"/");b.session.runNoHangup(c+e,function(a){a=Buffer.isBuffer(a)?a.toString():a;console.log("[gdbserver] "+a)},function(){a.verbose("gdbserver#run()#_launchGdbserver#__exit");process.exit(0)},
d)}.bind(this),function(c){a.verbose("gdbserver#run()#_portForward()");b.session.forward(this.port,t,c)}.bind(this),function(c){a.verbose("gdbserver#run()#_printForwardInfo()");var d=b.session.getDevice();console.log(" >> gdb can connect to [target remote",d.host+":"+this.port+"]\n");c()}.bind(this)],function(a,b){f(a,b)})},close:function(b,e,f){a.verbose("gdbserver#close()");e=b.port||defaultGdbserverPort;if("function"!==typeof f)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(f));
async.waterfall([function(a){b.nReplies=1;b.session=new novacom.Session(b.device,a)}.bind(this),function(a,b){this.session=a;b()}.bind(this),this.getPidUsingPort.bind(this,e),this.killProcByPid.bind(this),function(a){setTimeout(a,1E3)},this.closeSession],function(b,e){a.verbose("gdbserver#close()","err: ",b,"results:",e);f(b,e)})},getPidUsingPort:function(b,e){function f(a){(a=Buffer.isBuffer(a)?a.toString().trim():a.trim())?(a=a.split(" ").filter(function(a){return""!==a.trim()}),e(null,a)):e()}
a.verbose("gdbserver#getPidUsingPort()");"function"===typeof b&&(e=b,b=defaultGdbserverPort);if(this.session){var g=util.format("fuser -n tcp %s 2>/dev/null | awk '{print $0}' | xargs echo",b);async.series([function(a){this.session.run(g,process.stdin,f,process.stderr,a)}.bind(this)],function(a){if(a)return e(a)})}else e(Error("gdbserver#getPidUsingPort(): no session"))},killProcByPid:function(b,e){a.verbose("gdbserver#killProcByPid()");if("function"===typeof b)return b();if(!this.session)return e(Error("gdbserver#killProcByPid(): no session"));
var f=[];if(b instanceof Array)f=b;else if(b instanceof String)f.push(b);else return e(Error("gdbserver#killProcByPid(): no pid"));f=util.format("kill -9 %s 2>/dev/null",f.join(" "));this.session.runNoHangup(f,e)},closeSession:function(b){if(!this.session)return a.verbose("gdbserver#close()#closeSession()","This session is already terminated"),b();this.session.end();this.session=null;b()}};"undefined"!==typeof module&&module.exports&&(module.exports=g)})();
