var path=require("path"),promise=require("bluebird"),log=require("npmlog"),Table=require("easy-table"),fs=promise.promisifyAll(require("fs-extra")),readJsonSync=require("./util/json").readJsonSync,copyToDirAsync=require("./util/copy").copyToDirAsync,merge=require("./util/merge"),errHndl=require("./base/error-handler");
function Generator(b){function a(a){if(a){var c=path.join(__dirname,"..");a=fs.readFileSync(a);a=a.toString().replace(/\$cli-root/gi,c).replace(/\\/g,"/");f=JSON.parse(a)}else f=null}var f;a(b);this.setTmplates=a;this.getTemplates=function(){return f}}
Generator.prototype.showTemplates=function(b){var a=this.getTemplates(),f=new Table,h={webapp:"Web App",nativeapp:"Native App",webappinfo:"Web App Info",nativeappinfo:"Native App Info",jsservice:"JS Service",jsserviceinfo:"JS Service Info",packageinfo:"Package Info"},c;for(c in a)if(!0!==a[c].hide&&a[c].type){var g=a[c]["default"]?"(default) ":"",n=a[c].branch||"-",p=h[a[c].type]||a[c].type;b&&-1===["true","false",!0,!1].indexOf(b)&&a[c].type&&null===a[c].type.match(new RegExp(b+"$","gi"))||(f.cell("ID",
c),f.cell("Project Type",p),f.cell("Version",n),f.cell("Description",g+a[c].description),f.newRow())}console.log(f.print())};Generator.prototype.existOutDir=function(b){log.verbose("Generator#existOutDir()",b);try{if(0<fs.readdirSync(b).length)return!0}catch(a){if(a&&"ENOTDIR"===a.code)throw errHndl.changeErrMsg("NOT_DIRTYPE_PATH",b);if(a&&"ENOENT"===a.code)return log.verbose("Generator#existOutDir()","The directory does not exist"),!1;throw a;}};
Generator.prototype.generate=function(b){function a(a,c){var d=[].concat(a.path);return promise.all(d.map(function(a){return fs.lstatAsync(a).then(function(d){if(!d.isFile())throw errHndl.changeErrMsg("INVALID_PATH","meta template",a);d=fs.readFileSync(a,"utf8");d=d.replace(/(?:['"])([:/.A-z?<_&s=>0-9;-]+')/,"'"+c+"'");var b=path.join(l,path.basename(a));fs.writeFileSync(b,d,{encoding:"utf8"})})})).then(function(){log.verbose("Generator#generate()#_writeUrldata():","done")})["catch"](function(a){log.verbose("Generator#generate()#_writeUrldata()#err:",
a);throw a;})}function f(a,c,b,e){log.verbose("Generator#generate()#_writeMetadata()");var d=[].concat(a.path),f=c||{},q=b||{},k=e||{};return promise.all(d.map(function(d){return fs.lstatAsync(d).then(function(c){if(!c.isFile())throw errHndl.changeErrMsg("INVALID_PATH","meta template",d);c=path.basename(d);var b=readJsonSync(d);"appinfo.json"===c?b=merge(b,f):"services.json"===c?b=merge(b,q):"package.json"===c&&"jsserviceinfo"===a.type?b.name=g.id||b.name:"packageinfo.json"===c&&(b=merge(b,k));return b}).then(function(a){var b=
path.join(l,path.basename(d));return fs.mkdirsAsync(l).then(function(){return fs.writeFileSync(b,JSON.stringify(a,null,2),{encoding:"utf8"})})})})).then(function(){log.verbose("Generator#generate()#_writeMetadata():","done")})["catch"](function(a){log.verbose("Generator#generate()#_writeMetadata()#err:",a);throw a;})}var h=b.tmplName,c=b.pkginfo,g=b.svcinfo,n=b.svcName,p=b.out,m=this.getTemplates(),l=path.resolve(p),e=m[h],k=b.appinfo;if(!e)return promise.reject(errHndl.changeErrMsg("INVALID_TEMPLATE"));
e.metadata&&e.metadata.data&&"object"===typeof e.metadata.data&&(k=merge(k,e.metadata.data));n?(g.id=n,g.services=[{name:n}]):!n&&g.id&&(g.services=[{name:g.id}]);return promise.resolve().then(function(){log.verbose("Generator#generate()","template name:"+h);console.log("Generating "+h+" in "+l);var b;if(h.match(/(^hosted)/))return b=[].concat(e.path),promise.all(b.map(function(a){return copyToDirAsync(a,l)})).then(function(){var d,h;e.metadata&&e.metadata.id&&(d=m[e.metadata.id]);if(d){if(k.url){h=
k.url;delete k.url;var l={path:path.join(b[0],"index.html")};a(l,h)}return f(d,k,g,c)}});if(e.type.match(/info$/))return f(e,k,g,c);b=[].concat(e.path);return promise.all(b.map(function(a){log.verbose("Generator#generate()","template src:"+a);return copyToDirAsync(a,l)})).then(function(){var a;e.metadata&&e.metadata.id&&(a=m[e.metadata.id]);if(a)return f(a,k,g,c)})}).then(function(){return promise.all((m[h].deps||[]).map(function(a){if(m[a]){if(m[a].path)return copyToDirAsync(m[a].path,l);log.warn("Generator#generate()",
"Invalid template path "+a)}else log.warn("Generator#generate()","Invalid template id "+a)}))}).then(function(){log.verbose("Generator#generate():","done");return{msg:"Success"}})["catch"](function(a){log.verbose("Generator#generate()#err:",a);throw a;})};module.exports=Generator;
