var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[d]=a.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var d=0;return $jscomp.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(b,d){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var a=0,f={next:function(){if(a<b.length){var g=a++;return{value:d(g,b[g]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};
$jscomp.polyfill=function(b,d,a,f){if(d){a=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var g=b[f];g in a||(a[g]={});a=a[g]}b=b[b.length-1];f=a[b];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6-impl","es3");
var util=require("util"),async=require("async"),path=require("path"),npmlog=require("npmlog"),request=require("request"),luna=require("./base/luna"),novacom=require("./base/novacom"),server=require("./base/server"),sdkenv=require("./base/sdkenv"),errHndl=require("./base/error-handler"),hasProperty=require("./util/property"),installer=require("./install"),launcher=require("./launch"),defaultAppInsptPort="9998",defaultNodeInsptPort="8080",defaultServiceDebugPort="5885",platformNodeVersion="0",nodeBaseVersion=
"8";
(function(){var b=npmlog;b.heading="inspector";b.level="warn";var d={log:b,inspect:function(a,d,g){function f(e,d){var c=util.format("netstat -ltn 2>/dev/null | grep :%s | wc -l",e);async.series([a.session.run.bind(a.session,c,process.stdin,function(a){a=Buffer.isBuffer(a)?a.toString().trim():a.trim();if("0"===a)b.verbose("inspector#inspect()#_findNewDebugPort()","final dbgPort : "+e),d(null,e);else if("1"===a)e=Number(e)+1,f(e,d);else return d(errHndl.changeErrMsg("FAILED_GET_PORT"))},process.stderr)],function(a){a&&
d(a)})}function m(b){var e=0;async.series([a.session.run.bind(a.session,"node -v",process.stdin,function(a){1<++e||(platformNodeVersion=Buffer.isBuffer(a)?a.toString().trim():a.trim(),a=platformNodeVersion.split("."),platformNodeVersion=Number(a[0].slice(1)),b())},process.stderr)],function(a){a&&b(a)})}if("function"!==typeof g)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(g));a.svcDbgInfo={};a&&hasProperty(a,"serviceId")&&(a.serviceId instanceof Array?a.serviceId.forEach(function(b){a.svcDbgInfo[b]=
{}}):a.svcDbgInfo[a.serviceId]={});async.series([function(b){(new sdkenv.Env).getEnvValue("BROWSER",function(e,c){a.bundledBrowserPath=c;b()})},function(b){if(!a.serviceId)return b();installer.list(a,function(e,c){c instanceof Array&&(a.instPkgs=c);b(e)})},function(b){a.nReplies=1;a.session=new novacom.Session(a.device,b)},function(e){b.verbose("inspector#inspect()#_runApp");if(!a.appId||a.running)return e();launcher.listRunningApp(a,null,function(d,c){c=[].concat(c);var f=c.map(function(a){return a.id});
b.verbose("inspector#inspect()#_runApp#runAppIds",f.join(","));-1===f.indexOf(a.appId)?(b.verbose("inspector#inspect()#_runApp#launch",a.appId),launcher.launch(a,a.appId,{},e)):e()})},function(b){a.appId?a.session.forward(defaultAppInsptPort,a.hostPort||0,a.appId,b):b()},function(e){function d(b){var c=k.pop();if(!c)return b();request.get(l+c.reqPath,function(h,d,e){if(h||200!==d.statusCode)return b();h=JSON.parse(e);for(var f in h)if(-1!==h[f].url.indexOf(a.appId)||-1!==h[f].url.indexOf(a.localIP)){if(!h[f][c.propName])return b(errHndl.changeErrMsg("USING_WEBINSPECTOR"));
l+=h[f][c.propName];k=[];break}b()})}function c(a,b){"@@ARES_CLOSE@@"===a?(b.status(200).send(),g=setTimeout(function(){process.exit(0)},2E3)):"@@GET_URL@@"===a&&(clearTimeout(g),b.status(200).send(l))}function f(b,c){b?process.exit(1):c&&c.msg&&a.open&&server.openBrowser("http://localhost:"+c.port+"/ares_cli/ares.html",a.bundledBrowserPath)}var l,g,k=[{reqPath:"/pagelist.json",propName:"inspectorUrl"},{reqPath:"/json/list",propName:"devtoolsFrontendUrl"}];a.appId&&(l="http://localhost:"+a.session.getLocalPortByName(a.appId),
a.session.target.noPortForwarding&&(b.verbose("inspector#inspect()","noPortForwarding"),l="http://"+a.session.target.host+":9998"),async.whilst(function(){return 0<k.length},d.bind(this),function(a){if(a)return e(a);console.log("Application Debugging - "+l);server.runServer(__dirname,0,c,f)}));e()},function(d){var e=Object.keys(a.svcDbgInfo).filter(function(a){return"undefined"!==a});async.forEachSeries(e,function(c,d){if(!c)return d();var e=defaultServiceDebugPort,g=function(b,c){if(!a.svcDbgInfo[b].port)return c();
var k=a.session.getLocalPortByName(b),e=util.format("http://%s:%s/debug?port=%s","localhost",k,a.svcDbgInfo[b].port),d;request.get(e,function(b,k){function f(a,b){"@@ARES_CLOSE@@"===a?(b.status(200).send(),d=setTimeout(function(){process.exit(0)},2E3)):"@@GET_URL@@"===a&&(clearTimeout(d),b.status(200).send(e))}function h(b,c){b?process.exit(1):c&&c.msg&&a.open&&server.openBrowser("http://localhost:"+c.port+"/ares_cli/ares.html",a.bundledBrowserPath)}b||200!==k.statusCode||(console.log("nodeInsptUrl:",
e),server.runServer(__dirname,0,f,h),c())})};async.waterfall([function(b){a.instPkgs&&a.instPkgs.every(function(b){return-1!==c.indexOf(b.id)?(a.svcDbgInfo[c].path=path.join(path.dirname(b.folderPath),"..","services",c).replace(/\\/g,"/"),!1):!0});if(!a.svcDbgInfo[c].path)return b(errHndl.changeErrMsg("FAILED_GET_SVCPATH",c));b()},function(b){var e=path.join(a.svcDbgInfo[c].path,"services.json").replace(/\\/g,"/"),d;async.series([a.session.run.bind(a.session,"cat "+e,process.stdin,function(a){d=Buffer.isBuffer(a)?
a.toString().trim():a.trim();b(null,d)},process.stderr)],function(a){if(a)return b(errHndl.changeErrMsg("FAILED_FIND_SERVICE",c))})},function(a,b){try{if("native"===JSON.parse(a).engine)return b(errHndl.changeErrMsg("USE_GDB",c));b()}catch(n){b(n)}},function(b){a.nReplies=1;luna.send(a,{service:c,method:"quit"},{},function(){b()},b)},function(b){a.session.runNoHangup("mkdir -p "+a.svcDbgInfo[c].path+"/_ares",b)},f.bind(this,e),function(b,d){e=b;a.session.runNoHangup("echo "+e+" > "+a.svcDbgInfo[c].path+
"/_ares/debugger-port",d)},function(a){setTimeout(function(){a()},1E3)},function(b){a.svcDbgInfo[c].port=e;a.nReplies=1;luna.send(a,{service:c,method:"info"},{},function(){b()},b)},function(a){setTimeout(function(){a()},1E3)},m.bind(this),function(d){b.info("inspector#inspect()#doPortForward()","platformNodeVersion: "+platformNodeVersion+", nodeBaseVersion: "+nodeBaseVersion);platformNodeVersion<nodeBaseVersion?a.session.forward(defaultNodeInsptPort,a.hostPort||0,c,d):platformNodeVersion>=nodeBaseVersion&&
a.session.forward(e,a.hostPort||0,c,d)},function(b){a.session.runNoHangup("rm -rf "+a.svcDbgInfo[c].path+"/_ares",b)},function(b){if(platformNodeVersion<nodeBaseVersion)g(c,b);else if(platformNodeVersion>=nodeBaseVersion){a.open&&console.log('Cannot support "--open option" on platform node version 8 and later');var d='To debug your service, set "localhost:'+a.session.getLocalPortByName(c)+'" on Node Inspector Client(Chrome DevTools, Visual Studio Code, etc.).';console.log(d);b()}}],function(a,c){b.verbose("inspector#inspect()",
"err: ",a,"results:",c);d(a,c)})},function(a){d(a)})},function(a){b.verbose("inspector#inspect()","running...");setImmediate(a)}],function(a){setImmediate(g,a)})}};"undefined"!==typeof module&&module.exports&&(module.exports=d)})();
