var fs=require("fs"),path=require("path"),util=require("util"),npmlog=require("npmlog"),async=require("async"),streamBuffers=require("stream-buffers"),crypto=require("crypto"),luna=require("./base/luna"),novacom=require("./base/novacom"),Appdata=require("./base/cli-appdata"),errHndl=require("./base/error-handler"),hasProperty=require("./util/property");
(function(){var b=npmlog;b.heading="installer";b.level="warn";var r=new Appdata,u={log:b,install:function(a,g,d){if("function"!==typeof d)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(d));if(!g)return d(errHndl.changeErrMsg("EMPTY_VALUE","PACKAGE_FILE"));var t=path.basename(g),h={tempDirForIpk:"/media/developer/temp",removeIpkAfterInst:!0},l=r.getConfig(!0);if(l.install){var l=l.install,p;for(p in l)hasProperty(h,p)&&(h[p]=l[p])}var m=path.join(h.tempDirForIpk,t).replace(/\\/g,
"/"),c=new streamBuffers.WritableStreamBuffer,e=a.appId,q,k,n=200;a=a||{};b.info("installer#install():","installing "+g);async.waterfall([function(f){a.nReplies=0;a.session=new novacom.Session(a.device,f)},function(f,e){a.session=f;setImmediate(e)},function(f){if(a.opkg&&"root"!==a.session.getDevice().username)return setImmediate(f,errHndl.changeErrMsg("NEED_ROOT_PERMISSION","opkg install"));var e="/bin/rm -rf "+h.tempDirForIpk+" && /bin/mkdir -p "+h.tempDirForIpk;"root"===a.session.getDevice().username&&
(e+=" && /bin/chmod 777 "+h.tempDirForIpk);a.op=(a.session.target.files||"stream")+"Put";a.session.run(e,null,null,null,f)},function(f){console.log("Installing package "+g);a.session.put(g,m,f)},function(f){a.session.run('/bin/ls -l "'+m+'"',null,c,null,f)},function(a){b.verbose("installer#install():","ls -l:",c.getContents().toString());a()},function(a){var e=crypto.createHash("md5"),f=Buffer.alloc(n),c=0;async.waterfall([fs.lstat.bind(fs,g),function(a,e){a.size>n?c=a.size-n:(c=0,n=a.size);e()},
fs.open.bind(fs,g,"r"),function(a,b){fs.read(a,f,0,n,c,function(){e.update(f);b()})},function(){(q=e.digest("hex"))||b.warn("installer#install():","Failed to get md5sum from the ipk file");b.verbose("installer#install():","srcMd5:",q);a()}],function(e){a(e)})},function(e){function f(a){if(a=Buffer.isBuffer(a)?a.toString().trim():a.trim())k=a.split("-")[0].trim(),b.verbose("installer#install():","dstMd5:",k);k||b.warn("installer#install():","Failed to get md5sum from the transmitted file");e()}var c=
"/usr/bin/tail -c "+n+' "'+m+'" | /usr/bin/md5sum';async.series([function(e){a.session.run(c,null,f,null,e)}],function(a){if(a)return e(a)})},function(a){if(!q||!k)b.warn("installer#install():","Cannot verify transmitted file");else if(q!==k)return a(errHndl.changeErrMsg("FAILED_TRANSMIT_FILE"));a()},function(f){function c(e){function c(a){a=Buffer.isBuffer(a)?a.toString():a;console.log(a)}var f='/usr/bin/opkg install "'+m+'"',f=f.concat(a.opkg_param?" "+a.opkg_param:"");async.series([a.session.run.bind(a.session,
f,null,c,c),a.session.run.bind(a.session,"/usr/sbin/ls-control scan-services ",null,null,c)],function(a){if(a)return e(a);e(null,null)})}function k(c){var f=a.session.getDevice().lunaAddr.install,k=f.returnValue.split(".");luna.send(a,f,{id:e,ipkUrl:m,subscribe:!0},function(a,e){for(var f=a,c=1;c<k.length;c++)f=f[k[c]];f.match(/FAILED/i)?(b.verbose("installer#install():","failure"),e(errHndl.changeErrMsg("FAILED_CALL_LUNA",a.details&&a.details.reason?a.details.reason:f?f:""))):f.match(/installed|^SUCCESS/i)?
(b.verbose("installer#install():","success"),e(null,f)):(b.verbose("installer#install():","waiting"),e(null,null))},c)}(a.opkg?c:k)(f)},function(e,c){"function"===typeof e&&(c=e);h.removeIpkAfterInst?a.session.run('/bin/rm -f "'+m+'"',null,null,null,c):c()},function(e){a.session.end();a.session=null;e(null,{msg:"Success"})}],function(a,e){d(a,e)})},remove:function(a,g,d){if("function"!==typeof d)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(d));a=a||{};async.waterfall([function(b){a.nReplies=
void 0;a.session=new novacom.Session(a.device,b)},function(b,h){a.session=b;if(a.opkg&&"root"!==a.session.getDevice().username)return setImmediate(h,errHndl.changeErrMsg("NEED_ROOT_PERMISSION","opkg remove"));setImmediate(h)},function(d){function h(b){function d(a){a=Buffer.isBuffer(a)?a.toString():a;return b(Error(a))}var c="/usr/bin/opkg remove "+g,c=c.concat(a.opkg_param?" "+a.opkg_param:"");async.series([a.session.run.bind(a.session,c,null,function(a){a=Buffer.isBuffer(a)?a.toString():a;console.log(a);
if(a.match(/No packages removed/g))return b(errHndl.changeErrMsg("FAILED_REMOVE_PACKAGE",g));console.log(a.trim())},d),a.session.run.bind(a.session,"/usr/sbin/ls-control scan-services ",null,null,d)],function(a){if(a)return b(a);b(null,{})})}function l(d){var h=a.session.getDevice().lunaAddr.remove,c=h.returnValue.split("."),e=0;luna.send(a,h,{id:g,subscribe:!0},function(a,k){b.silly("installer#remove():","lineObj: %j",a);for(var d=a,f=1;f<c.length;f++)d=d[c[f]];d.match(/FAILED/i)?(b.verbose("installer#remove():",
"failure"),e||(e++,k(errHndl.changeErrMsg("FAILED_CALL_LUNA",a.details&&a.details.reason?a.details.reason:d?d:"")))):d.match(/removed|^SUCCESS/i)?(b.verbose("installer#remove():","success"),k(null,{status:d})):(b.verbose("installer#remove():","waiting"),k())},d)}(a.opkg?h:l)(d)}],function(a,b){a||(b.msg="Removed package "+g);d(a,b)})},list:function(a,g){if("function"!==typeof g)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(g));a=a||{};async.waterfall([function(b){a.nReplies=1;
a.session=new novacom.Session(a.device,b)},function(b,g){a.session=b;if(a.opkg&&"root"!==a.session.getDevice().username)return setImmediate(g,errHndl.changeErrMsg("NEED_ROOT_PERMISSION","opkg list"));setImmediate(g)},function(d){function g(b){function d(a){a=Buffer.isBuffer(a)?a.toString():a;console.log(a)}var g;g="/usr/bin/opkg list".concat(a.opkg_param?" "+a.opkg_param:"");async.series([a.session.run.bind(a.session,g,null,d,d)],function(a){if(a)return b(a);b(null,{})})}function h(d){var g=a.session.getDevice().lunaAddr.list,
h=g.returnValue.split(".");luna.send(a,g,{subscribe:!1},function(a,e){for(var d=a,c=1;c<h.length;c++)d=d[h[c]];if(Array.isArray(d)){for(c=0;c<d.length;c++)d[c].visible||(d.splice(c,1),c--);b.verbose("installer#list():","success");e(null,d)}else b.verbose("installer#list():","failure"),e(errHndl.changeErrMsg("INVALID_OBJECT"))},d)}(a.opkg?g:h)(d)}],function(a,b){g(a,b)})}};"undefined"!==typeof module&&module.exports&&(module.exports=u)})();
