var util=require("util"),async=require("async"),npmlog=require("npmlog"),path=require("path"),fs=require("fs"),semver=require("semver"),exec=require("child_process").exec,inspector=require("./inspect"),installer=require("./install"),luna=require("./base/luna"),novacom=require("./base/novacom"),errHndl=require("./base/error-handler"),fileWatcher=require("./base/file-watcher"),sdkenv=require("./base/sdkenv"),os=require("os");
(function(){var f=npmlog;f.heading="launcher";f.level="warn";var m={log:f,launch:function(a,h,k,g){if("function"!==typeof g)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(g));var c=!1,e=this;a=a||{};async.series([function(b){"Hosted"===a.installMode?installer.list(a,function(a,l){for(var d in l)if("com.sdk.ares.hostedapp"===l[d].id){c=!0;break}b(a)}):b()},function(b){"Hosted"===a.installMode?e.listRunningApp(a,null,function(d,l){for(var c in l)if("com.sdk.ares.hostedapp"===l[c].id){e.close(a,
"com.sdk.ares.hostedapp",null,b);return}b(d)}):b()},function(b){if("Hosted"!==a.installMode||c)b();else{var d=path.join(__dirname,"com.sdk.ares.hostedapp.ipk");a.appId=h;installer.install(a,d,b)}},function(b){a.nReplies=1;a.session=new novacom.Session(a.device,b)},function(b){"Hosted"===a.installMode?(a.session.runHostedAppServer(a.hostedurl,b),console.log("Ares Hosted App is now running...")):b()},function(b){if("Hosted"===a.installMode){if(a.hostIp)a.localIP=a.hostIp;else{var d=os.networkInterfaces(),
c="",e;for(e in d)for(var g=0;g<d[e].length;g++){var f=d[e][g];"IPv4"!==f.family||"127.0.0.1"===f.address||f.internal||(c=c||f.address,a.localIP=c)}}d=a.session.getHostedAppServerPort();null==k&&(k={});k.hostedurl="http://"+a.localIP+":"+d+"/"}b()},function(b){var d=a.session.getDevice().lunaAddr.launch,c=d.returnValue.split(".");luna.send(a,d,{id:h,subscribe:!1,params:k},function(a,b){f.silly("launcher#launch#_launch():","lineObj:",a);for(var d=a,e=1;e<c.length;e++)d=d[c[e]];d?(f.verbose("launcher#launch#_launch():",
"success"),b(null,{procId:d})):(f.verbose("launcher#launch#_launch():","failure"),b(errHndl.changeErrMsg("INVALID_OBJECT")))},b)},function(b){"Hosted"===a.installMode&&(f.verbose("launcher#launch#_runFileWatcher()"),a.appId=h,fileWatcher.watch(a));b()},function(b){f.verbose("launcher#launch#_runInspector()");a.inspect?(a.appId=h,a.running=!0,async.series([inspector.inspect.bind(inspector,a,null),function(){}],function(a){b(a)})):"Hosted"===a.installMode?(process.on("SIGINT",function(){f.verbose("launcher#launch#_runInspector():",
"SIGINT is detected in Hosted mode");b()}),!0===a.testMode&&b()):b()}],function(b,d){var c=d[6];if(!b)if("Hosted"!==a.installMode)c.msg="Launched application "+h;else{c.msg="";e.close(a,"com.sdk.ares.hostedapp",null,g);return}g(b,c)})},close:function(a,h,k,g){if("function"!==typeof g)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(g));a=a||{};async.series([function(c){a.nReplies=1;a.session=new novacom.Session(a.device,c)},function(c){var e=a.session.getDevice().lunaAddr.terminate,
b=e.returnValue.split(".");luna.send(a,e,{id:h,subscribe:!1},function(a,c){f.silly("launcher#close#_close():","lineObj:",a);for(var d=a,e=1;e<b.length;e++)d=d[b[e]];d?(f.verbose("launcher#close#_close():","success"),c(null,{procId:d})):(f.verbose("launcher#close#_close():","failure"),c(errHndl.changeErrMsg("INVALID_OBJECT")))},c)}],function(c,e){var b=e[1];!c&&b&&(b.msg="Hosted"!==a.installMode?"Closed application "+h:"...Closed Ares Hosted App");g(c,b)})},listRunningApp:function(a,h,k){if("function"!==
typeof k)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(k));a=a||{};async.waterfall([function(g){a.nReplies=1;a.session=new novacom.Session(a.device,g)},function(g,c){var e=a.session.getDevice().lunaAddr.running,b=e.returnValue.split(".");if(!e||!b)return c(errHndl.changeErrMsg("NOT_SUPPORT_RUNNINGLIST"));luna.send(a,e,{subscribe:!1},function(a,c){for(var d=a,e=1;e<b.length;e++)d=d[b[e]];d=d||[];a.returnValue?(f.verbose("launcher#listRunningApp():","success"),c(null,d)):(f.verbose("launcher#listRunningApp():",
"failure"),c(errHndl.changeErrMsg("INVALID_OBJECT")))},c)}],function(a,c){k(a,c)})},launchSimulator:function(a,h,k,g){if("function"!==typeof g)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(g));a=a||{};async.waterfall([function(c){(new sdkenv.Env).getEnvValue("SDK",function(e,b){a.simulatorDir=b?path.join(b,"Simulator"):path.resolve(__dirname,"../../../Simulator");if(fs.existsSync(a.simulatorDir))if(fs.statSync(a.simulatorDir).isDirectory()){console.log("Finding simulator in "+
a.simulatorDir);var d=fs.readdirSync(a.simulatorDir);c(null,d)}else return setImmediate(c,errHndl.changeErrMsg("NOT_DIRTYPE_PATH",a.simulatorDir));else return setImmediate(c,errHndl.changeErrMsg("NOT_EXIST_PATH",a.simulatorDir))})},function(c,e){a.simulatorPrefix="webOS_TV_"+a.webOSTV+"_Simulator";for(var b=[],d=0;d<c.length;d++)0===c[d].indexOf(a.simulatorPrefix)&&fs.statSync(path.resolve(a.simulatorDir,c[d])).isDirectory()&&b.push(c[d].slice(a.simulatorPrefix.length+1));if(0===b.length)return setImmediate(e,
errHndl.changeErrMsg("UNMATCHED_VERSION",a.simulatorPrefix));b=b.sort(semver.rcompare);a.simulatorVer=b[0];e()},function(c){var e="";switch(process.platform){case "win32":e="exe";break;case "linux":e="appimage";break;case "darwin":e="app"}var b=a.simulatorPrefix+"_"+a.simulatorVer,d=path.join(a.simulatorDir,b,b+"."+e);if(!fs.existsSync(d))return setImmediate(c,errHndl.changeErrMsg("NOT_EXIST_PATH",d));e="darwin"===process.platform?"open "+d+" --args "+h+" '"+JSON.stringify(k)+"'":d+" "+h+" '"+JSON.stringify(k)+
"'";f.verbose("launcher#launchSimulator#_launchSimulator():","cmd:",e);exec(e,function(a){if(a)return setImmediate(c,a);a={};a.msg="Launched "+path.basename(d);c(null,a)});setTimeout(function(){var a={};a.msg="Launched "+path.basename(d);c(null,a)},1E3)}],function(a,e){g(a,e)})}};"undefined"!==typeof module&&module.exports&&(module.exports=m)})();
