var log=require("npmlog"),async=require("async"),colors=require("colors"),util=require("util"),streamBuffers=require("stream-buffers"),novacom=require("./base/novacom"),hasProperty=require("./util/property"),msgNotFoundLog="There is no logs";
(function(){var l={log:log,printLog:function(c,l){function m(h){function d(b){log.verbose("log#_checkFilter()");var f="DEBUG INFO WARNING ERR CRIT SILENT".split(" "),g=!0,a=!0,d;c.id&&""!==c.id&&(a=c.id===b.id.trim());d=hasProperty(c.filters,b.tag)?c.filters[b.tag].toUpperCase():c.filters["*"].toUpperCase();d=f.indexOf({D:"DEBUG",I:"INFO",W:"WARNING",E:"ERR",C:"CRIT",S:"SILENT"}[d]);b=f.indexOf(b.level.toUpperCase());if(-1===d||-1===b||d>b)g=!1;log.silly("log#_checkFilter()","filterFlag:",g,", idFlag:",
a);return g&&a}function e(b){log.verbose("log#_printLog()");var f="["+(b.level+"|"+b.tag+"|"+b.id)+"] ";if(0!==b.text.trim().length){if(c.output)for(var d=c.output.split(":"),a=0;a<d.length;a++)"pid"===d[a]&&(f+="["),"tid"===d[a]&&(f+=":"),b[d[a]]&&(f+=b[d[a].toLowerCase()]+" "),"tid"===d[a]&&(f+="] ");f+=b.text;f=f[{DEBUG:"blue",INFO:"green",WARNING:"yellow",ERR:"red",CRIT:"cyan",SILENT:"gray"}[b.level.toUpperCase()]];console.log(f)}}(Buffer.isBuffer(h)?h.toString():h).split(/\r?\n/).forEach(function(b){log.verbose("log#_onLine()");
if(""!==b&&void 0!==b)if(b===msgNotFoundLog)log.warn(b);else{log.verbose("log#_splitLog()");var f,g=-1,a={time:"",monotonicTime:"",facility:"",process:"",pid:"",context:"",messageId:""};for(h in a)f=b.slice(++g).indexOf(" "),a[h]=b.slice(g,g+f),g+=f;a.time=(new Date(a.time)).toString();a.level=a.facility.split(".")[1]||"";a.facility=a.facility.split(".")[0]||"";a.tid=a.pid.slice(1,a.pid.length-1).split(":")[1]||"";a.pid=a.pid.slice(1,a.pid.length-1).split(":")[0]||"";b=b.slice(g);f=b.indexOf("} ");
b=[b.slice(0,f),b.slice(f+1)];a.text=b[b.length-1];a.id="";a.tag="";b=a.text.indexOf("/");f=a.text.indexOf(":");-1!==b&&-1!==f&&b<f&&(a.id=a.text.slice(0,b),a.tag=a.text.slice(b+1,f),a.text=a.text.slice(f+1));log.silly("log#_splitLog()","logObj:",a);c.since&&Date.parse(c.today)<Date.parse(a.time)&&d(a)?(log.silly("log#_onLine()","since:",c.since,", today:",Date.parse(c.today),", log time:",Date.parse(a.time)),e(a)):!c.since&&d(a)&&e(a)}})}function k(c,d){return c&&c.match(/^[0-9]+$/)?"d"===d&&0<=
c||"h"===d&&0<=c||("m"===d||"s"===d)&&0<=c?!0:!1:!1}async.waterfall([function(h){log.verbose("log#_makeSession");c.session=new novacom.Session(c.device,h)}.bind(this),function(h,d){if(c.since){log.verbose("log#_splitTime");var e=c.since.toLowerCase(),b,f,g,a;0<=e.indexOf("d")&&(b=e.substring(0,e.indexOf("d")));0<=e.indexOf("h")&&(f=e.substring(e.indexOf("d")+1,e.indexOf("h")));0<=e.indexOf("m")&&(g=e.substring(e.indexOf("h")+1,e.indexOf("m")));0<=e.indexOf("s")&&(a=e.substring(e.indexOf("m")+1,e.indexOf("s")));
if(b||f||g||a){if(b&&!k(b,"d")||f&&!k(f,"h")||g&&!k(g,"m")||a&&!k(a,"s"))return d(Error("Enter proper 'since' option it should be like \"1d1h1m1s\" having interger in front of 'd|h|m|s' letters"));var l=new streamBuffers.WritableStreamBuffer;c.session.run("/bin/date +%s",null,l,null,function(){var e=l.getContentsAsString(),e=new Date(1E3*e);k(b,"d")&&e.setDate(e.getDate()-b);k(f,"h")&&e.setHours(e.getHours()-f);k(g,"m")&&e.setMinutes(e.getMinutes()-g);k(a,"s")&&e.setSeconds(e.getSeconds()-a);c.today=
e;d(null)})}else return d(Error("Enter proper 'since' option it should be like \"1d1h1m1s\""))}else d(null)}.bind(this),function(h){var d={};d.since=c.since;d.id=c.id;d.output=c.output;d.filter=c.filter;d.follow=c.follow;d.logFilePath=c.logFilePath;log.verbose("log#_splitArguments()","_options:",d);for(var d="DIWECS".split(""),e={DEFAULT:"",TIME:"time",PROCESS:"time:process:pid:tid"},b={"*":"D"},f=0;f<c.filters.length;f++){var g=c.filters[f].split(":");if(2<g.length||2===g.length&&(""===g[0]||""===
g[1])||2===g.length&&-1===d.indexOf(g[1].toUpperCase()))return h(Error("Invalid filter expression"));b[g[0]]=g[1]||"D"}c.filters=b;c.output&&(hasProperty(e,c.output.toUpperCase())?c.output=e[c.output.toUpperCase()]:h(Error("Error, Invalid parameter to -o")));h(null)}.bind(this),function(h){log.verbose("log#_getLogs()");var d=c.logFilePath||"/media/developer/log/devlog";async.series([function(e){var b=util.format("test -e %s && ( wc -l %s | xargs tail %s -n ) || echo %s",d,d,c.follow,msgNotFoundLog);
log.verbose("log#_getLogs()","cmd: ",b);c.session.run(b,process.stdin,m,process.stderr,e)}],function(c){h(c)})}.bind(this)],function(c,d){l(c,d)})}};"undefined"!==typeof module&&module.exports&&(module.exports=l)})();
