(function(){function f(a){this.message=a;this.stack=Error().stack}var c={},d={EACCES:"Permission denied. Please check the directory permission",EADDRINUSE:"An attempt to bind a server to a local address failed. Please check the IP address or the port number",ECONNREFUSED:"Connection refused. Please check the device IP address or the port number",ECONNRESET:"Unable to connect to the device. Please check the device",ENOENT:"Please check if the path is valid",ENOTDIR:"Please check if the path is valid",
EROFS:"Please check if the path is valid",TIME_OUT:"Connection timed out. Please check the device IP address or the port number",NO_FREE_SPACE:"Installation failure. Please check if there is sufficient free space in the disk","Authentication failure":"ssh authentication failure. Please check the ssh connection info such as password, private key and username again","connect Unknown system":"Please check the device IP address or the port number","Unable to parse private key":"Wrong passphrase for ssh key. Please check passphrase again",
"Unable to request a pseudo-terminal":"Unable to open terminal (Target does not allow to open pty)",REQUIRED_FIELD:"Please input required field",INVALID_ID_RULE:"The app/pkg ID should consist of lowercase letters (a-z), numbers (0-9), plus (+) and minus (-) signs and periods (.)",INVALID_VERSION_RULE:"The app/pkg version number should consist of three non-negative integers, separated by dots.\n\t\t Each number cannot exceed 9 digits and cannot contain leading zeroes",NOT_EXCLUDE_APPINFO:"You cannot exclude the appinfo.json file",
NOT_RELATIVE_PATH_APPINFO:"The pathname must be relative to the directory where the appinfo.json file is located",NO_METAFILE:"No meta file (ex. appinfo.json, services.json) exists in the project directory",NO_COMPONENT_FILE:"There is no component file for webOS package. File:",NO_ACCOUNT:"Account directory is not supported. Please delete the 'account-templates.json' file.",OVER_APPCOUNT:"You can package only one application at once",INVALID_SERVICEID:"ServiceID must start with package id",FAILED_MINIFY:"Failed to minify code. Please check the source code",
INVALID_MAIN_FILE:"Failed to get executable file name from appinfo.json",INVALID_JSON_FORMAT:"Invalid JSON format",INVALID_ARGV:"Please check arguments",INVALID_INTERVAL:'Please use nonnegative integer value for the "time-interval" option',INVALID_TEMPLATE:"Invalid template name",INVALID_FILE:"Invalid file",INVALID_VALUE:"Invalid value",INVALID_DEVICENAME:"Invalid device name. Do not use letters starting with '%' or '$'",INVALID_OBJECT:"Object format error",INVALID_MODE:"Please specify an option, either '--add' or '--modify'",
INVALID_CSV_FORMAT:"Please change the file extension to .csv",INVALID_IP:"IP format error",EMPTY_PROFILE:"Profile is empty",EMPTY_VALUE:"Please specify a value",EXISTING_VALUE:"The specified value already exists",EXISTING_FILETYPE_PATH:"A file with the same name at the specified location already exists",SUPPORT_ONLY_IPK:"Only .ipk file is supported. Please check the file extension",NOT_DIRTYPE_PATH:"The specified path is not a directory",NOT_EXIST_PATH:"The specified path does not exist",NOT_EXIST_SSHKEY_PASSWD:"Private key file or password does not exist",
NOT_SUPPORT_ENYO:"Enyo app packaging is not supported",NOT_SUPPORT_AUTHTYPE:"Not supported auth type",NOT_SUPPORT_RUNNINGLIST:"Not supported method to get running app information",NOT_SUPPORT_GDBSERVER:"Not supported gdbserver on webOS TV version under 3.0",NOT_SUPPORT_XZ:"xz file is not supported. Only .ipk file packaged with the CLI is supported",NOT_USE_WITH_OPTIONS:"Do not use together with options",USE_WITH_OPTIONS:"Use together with options",USE_PKGID_PKGINFO:"packageId must be provided by using either the '--pkgid' or the '--pkginfofile' option",
USE_GDB:"Please use GDB to debug a native serivce",NOT_IMPLEMENTED:"Not implemented",NOT_HANDLE_FILE:"Don't know how to handle",NOT_OVERWRITE_DIR:"Cannot overwrite the directory",UNMATCHED_DEVICE:"No matched device",UNMATCHED_VERSION:"No matched version",CANNOT_REMOVE_DEVICE:"Cannot remove the device",FAILED_CALL_LUNA:"luna-send command failed",FAILED_GET_PORT:"Failed to get Debug port",FAILED_GET_SVCPATH:"Failed to get service installation path",FAILED_GET_SSHKEY:"Failed to get ssh private key",
FAILED_TRANSMIT_FILE:"File transmission error. Please try again",FAILED_CREATE_DIR:"Cannot create directory in the destination path - permission denied",FAILED_REMOVE_PACKAGE:"No packages installed or removed",FAILED_FIND_SERVICE:"Failed to find a service with the specified name",FAILED_GET_APPINFO:"Failed to get appinfo.json",CONNECTED_MULTI_DEVICE:"Multiple devices are connected by novacom. Please specify the target name",SET_DEFAULT_MULTI_DEVICE:"Multiple devices are set to default target. Please reset device list",
NEED_ROOT_PERMISSION:"Unable to connect to the target device. root access required",MISSING_CALLBACK:"Missing completion callback",USING_WEBINSPECTOR:"Web Inspector is already connected with another browser. Please close the previous connection",UNKNOWN_OPERATOR:"Unknown operator",UNABLE_USE_SFTP:"Unable to use sftp"};c.getErrMsg=function(a,e){if(Object.prototype.hasOwnProperty.call(d,a))return d[a][e]};c.changeErrMsg=function(a,e,c){if(!a)return a;var b,g;for(g in d)if(a.toString()===g){b=d[g];e&&
(b=b+" <"+e+">");c&&(b=b+" : "+c);break}return b?new f(b):a};f.prototype=Object.create(Error.prototype);f.prototype.name="CLI";"undefined"!==typeof module&&module.exports&&(module.exports=c)})();
