var fs=require("fs"),path=require("path"),util=require("util"),stream=require("stream"),net=require("net"),mkdirp=require("mkdirp"),async=require("async"),log=require("npmlog"),Ssh2=require("ssh2"),shelljs=require("shelljs"),request=require("request"),server=require("./server"),errHndl=require("./error-handler"),Appdata=require("./cli-appdata");
(function(){function p(a,b,c){var d=null;if(0!==b||c)d=Error("Command '"+a+"' exited with code="+b+" (signal: "+c+")"),d.code=b,d.signal=c;return d}function q(){this.devices=[];this.deviceFileContent=null;m=new Appdata}var n={};"undefined"!==typeof module&&module.exports&&(module.exports=n);log.heading="novacom";log.level="warn";n.log=log;var l=path.resolve(process.env.HOME||process.env.USERPROFILE,".ssh"),m;n.Resolver=q;n.Resolver.prototype={load:function(a){var b=this;log.verbose("Resolver#load()");
async.waterfall([function(a){log.silly("Resolver#load#_replaceBuiltinSshKey()");var b=path.join(__dirname,"../../files/conf/","webos_emul"),c=path.join(l,"webos_emul");fs.stat(b,function(d,e){d?"ENOENT"===d.code?setImmediate(a):setImmediate(a,d):fs.stat(c,function(d,h){d?"ENOENT"===d.code?mkdirp(l,function(){shelljs.cp("-rf",b,l);fs.chmodSync(c,"0600");setImmediate(a)}):setImmediate(a,d):(e.mtime.getTime()>h.mtime.getTime()&&(shelljs.cp("-rf",b,l),fs.chmodSync(c,"0600")),setImmediate(a))})})}.bind(b),
function(a){log.silly("Resolver#load#_adjustList()");var b=m.getDeviceList(!0);1>b.filter(function(a){return void 0!==a["default"]}).length&&(log.silly("Resolver#load#_adjustList()","rewrite default field"),b=b.map(function(a){a["default"]="emulator"===a.name?!0:!1;return a}),this.save(b));setImmediate(a)}.bind(b),function(a){log.silly("Resolver#load#_loadString()");var d=m.getDeviceList(!0);Array.isArray(d)?(log.silly("Resolver#load#_loadString()","inDevices:",d),async.forEach(d,function(a,d){async.series([b._loadOne.bind(b,
a),b._addOne.bind(b,a)],d)},function(b){b?setImmediate(a,b):setImmediate(a)})):setImmediate(a,errHndl.changeErrMsg("INVALID_FILE"))}.bind(b)],function(c){c?setImmediate(a,c):(log.silly("Resolver#load()","devices:",b.devices),setImmediate(a))})},_loadOne:function(a,b){log.silly("Resolver#_loadOne()");"string"===typeof a.privateKey?(a.privateKeyName=a.privateKey,a.privateKey=Buffer.from(a.privateKey,"base64"),setImmediate(b)):"object"===typeof a.privateKey&&"string"===typeof a.privateKey.openSsh?(a.privateKeyName=
a.privateKey.openSsh,async.waterfall([fs.readFile.bind(this,path.join(l,a.privateKey.openSsh),b),function(b,d){a.privateKey=b;setImmediate(d)}],function(c){c&&(log.verbose("Resolver#_loadOne()","Unable to find SSH private key named '"+a.privateKey.openSsh+"' from '"+l+" for '"+a.name+"'"),a.privateKey=void 0);setImmediate(b)})):"webospro"===a.type?setImmediate(b,errHndl.changeErrMsg("NOT_IMPLEMENTED","webOS Pro device type handling")):(a.password||log.verbose("Resolver#_loadOne()","Regist privateKey : need to set a SSH private key in "+
l+" for'"+a.name+"'"),a.privateKeyName=void 0,a.privateKey=void 0,setImmediate(b))},_addOne:function(a,b){a.display={name:a.name,type:a.type,privateKeyName:a.privateKeyName,passphrase:a.passphrase,description:a.description,conn:a.conn||["ssh"],devId:a.id||null};a.username&&a.host&&a.port&&(a.display.addr="ssh://"+a.username+"@"+a.host+":"+a.port);for(var c in a)"display"!==c&&(a.display[c]=a[c]);log.silly("Resolver#_addOne()");this.devices=this.devices.filter(function(b){return b.name!==a.name});
c=m.getCommandService();a.lunaSend=c[a.type].lunaSend;a.lunaAddr=c[a.type].lunaAddr;this.devices.push(a);setImmediate(b)},save:function(a,b){log.verbose("Resolver#save()");log.silly("Resolver#save()","devicesData:",a);return m.setDeviceList(a,b)},list:function(a){log.verbose("Resolver#list()");setImmediate(a,null,this.devices.map(function(a){return a.display}))},setTargetName:function(a,b){var c="string"===typeof a?a:a&&a.name;if(!c){c=this.devices.filter(function(a){return a.conn&&-1!==a.conn.indexOf("novacom")});
if(1<c.length)return b(errHndl.changeErrMsg("CONNECTED_MULTI_DEVICE"));if(0<c.length&&c[0].name)c=c[0].name;else{c=this.devices.filter(function(a){return a["default"]&&!0===a["default"]});if(1<c.length)return b(errHndl.changeErrMsg("SET_DEFAULT_MULTI_DEVICE"));c=1===c.length?c[0].name:"emulator"}}b(null,"name",c)},getDeviceBy:function(a,b,c){log.verbose("Resolver#getDeviceBy()","key:",a,", value:",b);var d=this.devices.filter(function(d){return d[a]&&d[a]===b});if(1>d.length)setImmediate(c,errHndl.changeErrMsg("UNMATCHED_DEVICE",
a,b));else if(log.silly("Resolver#getDeviceBy()","devices:",d),"function"===typeof c)log.silly("Resolver#getDeviceBy()","async"),setImmediate(c,null,d[0]);else return log.silly("Resolver#getDeviceBy()","sync"),d[0]},getSshPrvKey:function(a,b){var c="string"===typeof a?a:a&&a.name;c?async.waterfall([this.getDeviceBy.bind(this,"name",c),function(a,b){log.info("Resolver#getSshPrvKey()","targetDevice.host:",a.host);var c="http://"+a.host+":9991/webos_rsa",d=a.name.replace(/(\s+)/gi,"_")+"_webos",e=path.join(l,
d);request.head(c,function(a,f){if(a||f&&200!==f.statusCode)return setImmediate(b,errHndl.changeErrMsg("FAILED_GET_SSHKEY"));log.info("Resolver#getSshPrvKey()#head","content-type:",f.headers["content-type"]);log.info("Resolver#getSshPrvKey()#head","content-length:",f.headers["content-length"]);request(c).pipe(fs.createWriteStream(e)).on("close",function(a){if(a)return setImmediate(b,errHndl.changeErrMsg("FAILED_GET_SSHKEY"));setImmediate(b,a,e,d)})})},function(a,b,c){log.info("Resolver#getSshPrvKey()",
"SSH Private Key:",a);console.log("SSH Private Key:",a);fs.chmodSync(a,"0600");setImmediate(c,null,b)}],b):setImmediate(b,errHndl.changeErrMsg("EMPTY_VALUE","DEVICE_NAME"))},modifyDeviceFile:function(a,b,c){var d=m.getDeviceList(!0),e="emulator";log.verbose("modifyDeviceFile():","op:",a);log.verbose("modifyDeviceFile():","targt:",b);if(!b.name)return setImmediate(c,errHndl.changeErrMsg("EMPTY_VALUE","target"));if(!Array.isArray(d))return setImmediate(c,errHndl.changeErrMsg("INVALID_FILE"));var f=
d.filter(function(a){var c=!1;b.name===a.name&&(b.profile?b.profile===a.profile&&(c=!0):c=!0);return c});log.verbose("modifyDeviceFile():","matchedDevices:",f);if("add"===a){if(0<f.length)return setImmediate(c,errHndl.changeErrMsg("EXISTING_VALUE","DEVICE_NAME",b.name));for(var g in b)"@DELETE@"===b[g]&&delete b[g];!0===b["default"]?e=b.name:!1===b["default"]&&(e=null);d=d.concat(b)}else if("remove"===a||"modify"===a||"default"===a){if(0===f.length)return setImmediate(c,errHndl.changeErrMsg("INVALID_VALUE",
"DEVICE_NAME",b.name));if("remove"===a){var k=!1,d=d.filter(function(a){if(b.name===a.name){if(!0===a.indelible)return k=!0;!1===a["default"]&&(e=null);return!1}return!0});if(k)return setImmediate(c,errHndl.changeErrMsg("CANNOT_REMOVE_DEVICE",b.name))}else"modify"===a?d=d.map(function(a){if(b.name===a.name){e=!0===a["default"]?a.name:null;for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c],"@DELETE@"===a[c]&&delete a[c])}return a}):"default"===a&&d.map(function(a){b.name===a.name&&
!0===b["default"]&&(e=b.name)})}else return setImmediate(c,errHndl.changeErrMsg("UNKNOWN_OPERATOR",a));null!=e&&(d=d.map(function(a){a["default"]=e===a.name?!0:!1;return a}));this.save(d,c)}};n.Session=function(a,b){if("function"!==typeof b)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(b));log.info("novacom.Session()","opening session to '"+("string"===typeof a?a:a&&a.name)+"'");this.resolver=new q;async.waterfall([this.resolver.load.bind(this.resolver),this.resolver.setTargetName.bind(this.resolver,
a),this.resolver.getDeviceBy.bind(this.resolver),this.checkConnection.bind(this),this.begin.bind(this)],b)};n.Session.prototype={checkConnection:function(a,b){var c=!1;if(a&&a.host&&a.port){var d=new net.Socket;d.setTimeout(2E3);var e=d.connect({host:a.host,port:a.port});e.on("connect",function(){c=!0;e.end();setImmediate(b,null,a)});e.on("error",function(a){e.destroy();setImmediate(b,errHndl.changeErrMsg(a))});e.on("timeout",function(){e.destroy();c||setImmediate(b,errHndl.changeErrMsg("TIME_OUT"))})}else setImmediate(b,
null,a)},begin:function(a,b){function c(a){setImmediate(b,errHndl.changeErrMsg(a),this)}function d(){log.verbose("Clear Session");e.end();setTimeout(function(){process.exit()},500)}log.verbose("Session#begin()","target:",a.display);var e=this;this.target=a||this.target;if(this.target.conn&&-1===this.target.conn.indexOf("ssh"))return setImmediate(b,null,this),this;this.ssh||(this.forwardedPorts=[],this.ssh=new Ssh2,this.ssh.on("connect",function(){log.verbose("Session#begin()","ssh session event: connected")}),
this.ssh.on("ready",c.bind(this)),this.ssh.on("error",c.bind(this)),this.ssh.on("end",function(){log.verbose("Session#begin()","ssh session event: end")}),this.ssh.on("close",function(a){log.verbose("Session#begin()","ssh session event: close (had_error:",a,")")}),this.target.readyTimeout=3E4,this.ssh.connect(this.target),process.on("SIGHUP",d),process.on("SIGINT",d),process.on("SIGQUIT",d),process.on("SIGTERM",d),process.on("exit",function(){d()}));return this},getDevice:function(){return this.target},
end:function(){log.verbose("Session#end()");this.ssh&&this.ssh.end();return this},_checkSftp:function(a){this.ssh.subsys("sftp",function(b,c){if(b)return setImmediate(a,b);c.once("data",function(b){if(b.toString().match(RegExp("sftp-server(.| )+not found","gi")))return b=errHndl.changeErrMsg("UNABLE_USE_SFTP"),b.code=4,setImmediate(a,b)})})},put:function(a,b,c){log.verbose("Session#put()","uploding into device:",b,"from host:",a);var d,e=this;log.verbose("Session#put()","sftpPut() :: start");e.sftpPut(a,
b,function(f){f?(log.verbose(f),4===f.code||127===f.code?(log.verbose("Session#put()","sftp is not available, attempt transfering file via streamPut"),d=fs.createReadStream(a),e.streamPut(b,d,c)):(14===f.code&&(f=errHndl.changeErrMsg("NO_FREE_SPACE")),setImmediate(c,f))):(log.verbose("Session#put()","sftpPut() :: done"),setImmediate(c))})},streamPut:function(a,b,c){log.verbose("Session#streamPut()","streaming into device:"+a);this.run('/bin/cat > "'+a+'"',b,null,process.stderr,c)},sftpPut:function(a,
b,c){log.verbose("Session#sftpPut()","host:"+a+" => device:"+b);var d=this;d._checkSftp(c);async.series({transfer:function(c){d.ssh.sftp(function(d,e){if(d)return setImmediate(c,d);var f=fs.createReadStream(a),h=e.createWriteStream(b);h.on("close",function(){e.end();setImmediate(c)});h.on("exit",function(a,b){d=p("sftpPut",a,b);setImmediate(c,d)});h.on("error",function(a){log.verbose("Session#sftpPut()","error:",a);setImmediate(c,a)});f.pipe(h)})}},function(a){setImmediate(c,a)})},run:function(a,
b,c,d,e){this.run_ssh(a,b,c,d,e)},run_ssh:function(a,b,c,d,e){log.verbose("Session#run()","cmd: "+a);if("function"!==typeof e)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(e));var f={},g={};c?c instanceof stream.Stream?(log.silly("Session#run()","stdout: stream"),f.stdout=c.write,g.stdout=c):c instanceof Function?(log.silly("Session#run()","stdout: function"),f.stdout=c):setImmediate(e,errHndl.changeErrMsg("INVALID_VALUE","stdout",util.inspect(c))):(log.silly("Session#run()","stdout: none"),
f.stdout=function(){});d?d instanceof stream.Stream?(log.silly("Session#run()","stderr: stream"),f.stderr=d.write,g.stderr=d):d instanceof Function?(log.silly("Session#run()","stderr: function"),f.stderr=d):setImmediate(e,errHndl.changeErrMsg("INVALID_VALUE","stderr",util.inspect(d))):(log.silly("Session#run()","stderr: none"),f.stderr=function(){});this.ssh.exec(a,function(k,h){log.silly("Session#run()","exec cmd: "+a);if(k)return log.verbose("Session#run()","exec err:"+k),setImmediate(e,k);h.on("data",
function(a,b){b=b||"stdout";log.verbose("Session#run()","on data ("+b+")");f[b].bind(g[b])(a)}).stderr.on("data",function(a){log.verbose("Session#run()","on data (stderr)");f.stderr.bind(g.stderr)(a)});h.on("end",function(){log.verbose("Session#run()","event end");c!==process.stdout&&c instanceof stream.Stream&&c.end();d!==process.stderr&&d instanceof stream.Stream&&d.end()});h.on("exit",function(b,c){log.verbose("Session#run()","event exit, code="+b+", signal="+c);k=p(a,b,c);setImmediate(e,k)});
h.on("close",function(){log.verbose("Session#run()","event close");void 0===k&&setImmediate(e)});b&&(b.pipe(h),log.silly("Session#run()","resuming input"))})},runNoHangup:function(a,b,c,d){this.runNoHangup_ssh(a,b,c,d)},runNoHangup_ssh:function(a,b,c,d){log.verbose("Session#runNoHangup()","cmd="+a);if(2>arguments.length)throw errHndl.changeErrMsg("MISSING_CALLBACK","next");for(var e in arguments)"undefined"===typeof arguments[e]&&(delete arguments[e],arguments.length--);switch(arguments.length){case 2:d=
b;b=c=null;break;case 3:d=c,c=b,b=null}if("function"!==typeof d)throw errHndl.changeErrMsg("MISSING_CALLBACK","next",util.inspect(d));this.ssh.exec(a,function(e,g){log.verbose("Session#run()","exec cmd: "+a+", err:"+e);if(e)return setImmediate(d,e);g.on("data",function(a){var c=Buffer.isBuffer(a)?a.toString():a;log.verbose("[Session#runNoHangup()#onData]",c);b&&b(a)}).stderr.on("data",function(a){var c=Buffer.isBuffer(a)?a.toString():a;log.verbose("Session#runNoHangup()#onData#stderr#",c);b&&b(a)});
if(c)g.on("exit",function(b,d){log.verbose("Session#runNoHangup()","event exit code="+b+", signal="+d+" (cmd: "+a+")");e=p(a,b,d);c(e)});setImmediate(d)})},forward:function(a,b,c,d){log.verbose("Session#forward()","devicePort:",a,"localPort:",b);var e=this,f=!1,g=null;"function"===typeof c?d=c:c&&(g=c);0!==b?0<e.forwardedPorts.indexOf({name:g,local:b,device:a})&&(f=!0):0<e.forwardedPorts.filter(function(b){return b.device===a&&b.name===g}).length&&(f=!0);if(f)return setImmediate(d);var k=net.createServer(function(c){log.info("Session#forward()",
"new client, localPort:",b);log.verbose("Session#forward()","new client, from: "+c.remoteAddress+":"+c.remotePort);c.on("error",function(a){log.verbose("Session#forward()","inCnx::error, err:: "+a)});e.ssh.forwardOut("127.0.0.1",c.remotePort,"127.0.0.1",a,function(d,e){d?(console.log("Session#forward()","failed forwarding client localPort:",b,"(inCnx.remotePort:",c.remotePort,")=> devicePort:",a),log.warn("Session#forward()","failed forwarding client localPort:",b,"=> devicePort:",a),c.destroy()):
(log.info("Session#forward()","connected, devicePort:",a),c.on("data",function(a){e.writable&&!0===e.writable&&!1===e.write(a)&&c.pause()}),c.on("close",function(a){log.verbose("Session#forward()","inCnx::close, had_err:",a);e.destroy()}),e.on("drain",function(){c.resume()}),e.on("data",function(a){c.write(a)}),e.on("close",function(a){log.verbose("Session#forward()","outCnx::close, had_err:",a)}))})});e.ssh.on("close",function(){k.close()});try{k.listen(b,null,function(){var b=k.address().port;e.forwardedPorts.push({name:g,
local:b,device:a});setImmediate(d)})}catch(h){setImmediate(d,h)}},getLocalPortByName:function(a){var b=null;this.forwardedPorts.forEach(function(c){c.name===a&&(b=c.local)});return b},runHostedAppServer:function(a,b){server.runServer(a,0,function(a,d){d&&d.port&&this.setHostedAppServerPort(d.port);b(a)}.bind(this))},setHostedAppServerPort:function(a){this.hostedAppServerPort=a},getHostedAppServerPort:function(){return this.hostedAppServerPort}}})();
